# Generated by Django 4.2.3 on 2023-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('expiration', models.IntegerField()),
                ('quality', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
