# Generated by Django 4.2.3 on 2023-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.IntegerField(null=True),
        ),
    ]
